# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 823a85b44fac70710a1b3c8a2a7b524ea1e57c41986f109ba99cfb754e3cd3b44c27bb3d5487fc4e33809f30263df27cdb9d73574de20c741054f683336f3f85

test:
  secret_key_base: a54055cc98a64da7184d2045b0ef486af04991221620d6f28195b21d7774273afca758699c55744c771d155d2155681e2bc739058b18b5978d1b90bcfb8d1717

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
